apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    database: dbvenda
    empresa: idinaldo
spec:
  containers:
  - name: mysql-image
    image: mysql:8.0.33
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: teteo
    - name: MYSQL_DATABASE
      value: dbInfnet
    - name: MYSQL_HOST
      value: mysql
    ports:
    - containerPort: 3306